name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
    
      - name: Restore
        run: dotnet restore IT.Collections.Factory.sln
    
      - name: Build
        run: dotnet build IT.Collections.Factory.sln --configuration Release --no-restore 
        
      - name: Test
        run: dotnet test IT.Collections.Factory.Tests/IT.Collections.Factory.Tests.csproj --no-restore

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish IT.Collections.Factory
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Collections.Factory/IT.Collections.Factory.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: true
